name: Step 0 # Start Course

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

jobs:
  start_course:
    name: Start Course
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: main
            fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Deactivate 'Start Course' button
        run: | 
          # Remove href from 'Start Course' button
          target='id="copy-course"[^>]*href="[^"]*"'
          replacement='id="copy-course"'
          sed -i "s|$target|$replacement|g" README.md

          # Change color from green to gray
          target=Copy_Course-008000
          replacement=Copy_Course-AAA
          sed -i "s|$target|$replacement|g" README.md

      - name: Activate 'Start Lesson' button
        run: |
          # Add link to issue
          target='id="start_lesson"'
          replacement='id="start_lesson" href="../../issues/1"'
          sed -i "s|$target|$replacement|g" README.md

          # Change color from gray to green
          target=Start_Lesson-AAA
          replacement=Start_Lesson-008000
          sed -i "s|$target|$replacement|g" README.md

      - name: Replace relative links in readme
        run: |
          target=../../
          replacement=https://github.com/${{ github.repository }}/
          sed -i "s|$target|$replacement|g" README.md

      - name: Push README changes
        run: |
          git add README.md
          git commit --message="Start course"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_step_1_content:
    name: Post step 1 content
    # needs: start_course
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: main
            fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Create new issue for learning
        run: |
          gh issue create \
          --title "Introduction to GitHub" \
          --body "Welcome to your learning course!
          As you complete each step, our bot will post comments, check your work, and share the next steps. Good luck!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add issue comment with step 1 content
        run: |
          # Load step 1 content
          next_step_content=$(cat steps/1-create-a-branch.md)
          
          # Update image links to be absolute
          target='steps/'
          replacement='https://github.com/${{ github.repository }}/blob/main/steps/'
          next_step_content=$(echo "$next_step_content" | sed "s|$target|$replacement|g")
          
          # Append "?raw=true" to image links
          target='.png'
          replacement='.png?raw=true'
          next_step_content=$(echo "$next_step_content" | sed "s|$target|$replacement|g")
          
          # Add content to issue
          gh issue comment 1 --body "$next_step_content"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Inform user about review
        run: |
          message="Waiting to check your work. ðŸ¤“"
          gh issue comment 1 --body "$message"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current lesson and start next one.
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}